Repository deskull-m/bakabakaband, pull requests merged in 2021-10, with the labels that each got.

#1132 [Add][Fix] ドワーフの守護者 / Dwarven defender 追加および島絞作のフレーバ修正．
  lib/edit/r_info.txt
Labels: enhancement

#1133 [Implement] 時空崩壊度の分経過加算を実装．計算数値を100万分率かつ型をint32_tに．
  src/load/load.cpp
  src/save/save.cpp
  src/world/world-turn-processor.cpp
  src/world/world.cpp
  src/world/world.h
Labels: enhancement

#1136 Merge/hengband20211002
  lib/help/joption.txt
  lib/help/option.txt
  lib/pref/pref-opt.prf
  src/blue-magic/blue-magic-checker.cpp
  src/blue-magic/learnt-power-getter.cpp
  src/blue-magic/learnt-power-getter.h
  src/cmd-action/cmd-mane.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/core/player-processor.cpp
  src/core/scores.cpp
  src/effect/effect-player.cpp
  src/game-option/birth-options.cpp
  src/game-option/birth-options.h
  src/game-option/option-types-table.cpp
  src/game-option/option-types-table.h
  src/io-dump/special-class-dump.cpp
  src/load/option-loader.cpp
  src/main-win/main-win-cfg-reader.h
  src/main-win/main-win-sound.cpp
  src/main-win/main-win-utils.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mind/mind-blue-mage.cpp
  src/monster-attack/monster-attack-player.cpp
  src/mspell/monster-power-table.cpp
  src/mspell/monster-power-table.h
  src/mspell/mspell-attack.cpp
  src/mspell/mspell-summon.cpp
  src/player/player-damage.cpp
  src/player/player-status.cpp
  src/spell-realm/spells-hex.cpp
  src/spell/spells-summon.cpp
  src/status/bad-status-setter.cpp
  src/status/bad-status-setter.h
  src/system/h-system.h
  src/term/term-color-types.h
  src/timed-effect/player-stun.cpp
  src/timed-effect/player-stun.h
  src/util/int-char-converter.h
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spoiler.cpp
Labels: enhancement

#1137 [Add] オソメ・ブラザーズ / Osome Brothers 二体追加．
  lib/edit/r_info.txt
Labels: enhancement

#1142 [Mofify] 煽るようなエラーメッセージ廃止。
  lib/file/error.txt
  lib/file/error_j.txt
  src/io/input-key-processor.cpp
Labels: enhancement

#440 [Implement] カオスフレームを「アライアンス」と命名の上実装開始．まずクラス作成．
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  lib/edit/r_info.txt
  src/Makefile.am
  src/alliance/alliance.cpp
  src/alliance/alliance.h
  src/info-reader/race-reader.cpp
  src/system/h-config.h
  src/system/monster-race-definition.h
  src/view/display-lore.cpp
Labels: enhancement

#1159 [Add] しっと団団員 / Sitto-Dan combatant
  lib/edit/r_info.txt
Labels: enhancement

#1166 [Add] ホビットの民兵/Hobbit militia 追加。既存のホビットモンスターにHOBBITフラグを付加。
  lib/edit/r_info.txt
Labels: enhancement

#1168 [Refactor] アライアンスリストをstd::mapに変更。
  src/alliance/alliance.cpp
  src/alliance/alliance.h
  src/info-reader/race-reader.cpp
  src/view/display-lore.cpp
Labels: Refactor

#1169 [Add] v_infoに生成階とレアリティ追加．
  lib/edit/v_info.txt
  src/info-reader/vault-reader.cpp
  src/room/rooms-vault.cpp
  src/room/rooms-vault.h
Labels: enhancement

#1171 Merge/hengband20211005
  src/artifact/fixed-art-generator.cpp
  src/info-reader/fixed-map-parser.cpp
  src/load/item-loader.cpp
  src/load/option-loader.cpp
  src/lore/lore-calculator.cpp
  src/main-win.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/pet/pet-util.cpp
  src/player/player-damage.cpp
  src/player/player-move.cpp
  src/player/player-status.cpp
  src/realm/realm-arcane.cpp
  src/realm/realm-chaos.cpp
  src/realm/realm-craft.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-death.cpp
  src/realm/realm-demon.cpp
  src/realm/realm-hissatsu.cpp
  src/realm/realm-names-table.h
  src/realm/realm-nature.cpp
  src/realm/realm-song.cpp
  src/realm/realm-sorcery.cpp
  src/realm/realm-trump.cpp
  src/spell-kind/spells-polymorph.cpp
  src/store/cmd-store.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: enhancement

#1174 [Add] 「現在の知識を確認する」に「各アライアンスからの印象値」を初期追加。
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  src/Makefile.am
  src/alliance/alliance.cpp
  src/cmd-io/cmd-knowledge.cpp
  src/knowledge/knowledge-alliance.cpp
  src/knowledge/knowledge-alliance.h
Labels: enhancement

#1179 [Add] Web向けアイコン追加．
  bakabakaband.ico
  bakabakaband180.png
  bakabakaband256.png
  index.html
Labels: documentation

#1177 [Release] 0.0.0Alpha21
  doxygen/Bakabakaband.doxyfile
  src/system/angband-version.h
Labels: release

#1180 [Add] 0.0.0Alpha21リリース情報追加．
  index.html
Labels: enhancement

#1185 [Add] モンスター種族ごとの基本最大数を MOB_* で指定可能にした。
  lib/edit/r_info.txt
  src/birth/game-play-initializer.cpp
  src/info-reader/race-reader.cpp
  src/knowledge/knowledge-monsters.cpp
  src/view/display-lore.cpp
Labels: enhancement

#1196 [Implement] モンスターに新しく動員数を定義。
  src/birth/game-play-initializer.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/dungeon.cpp
  src/dungeon/quest-monster-placer.cpp
  src/dungeon/quest.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/object-allocator.cpp
  src/info-reader/race-reader.cpp
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-uniques.cpp
  src/load/load-zangband.cpp
  src/load/lore-loader.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-remover.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-damage.cpp
  src/monster/monster-list.cpp
  src/mspell/mspell-selector.cpp
  src/mspell/mspell-summon.cpp
  src/mspell/specified-summon.cpp
  src/save/monster-writer.cpp
  src/system/monster-race-definition.h
  src/view/display-lore.cpp
  src/wizard/wizard-game-modifier.cpp
Labels: enhancement

#1202 [Modify] ハイ=エルフ・レンジャーをテレリ族のレンジャーとし、別にアヴァリ族のレンジャーを追加。アライアンスを調整。
  lib/edit/r_info.txt
Labels: enhancement

#1207 [Fix] 死亡回数のダンプ抜け修正。時空崩壊度を小数点6桁までダンプで表示。
  src/info-reader/race-reader.cpp
  src/system/monster-race-definition.h
  src/view/display-player-middle.cpp
  src/view/display-player.cpp
  src/view/display-util.cpp
  src/view/status-first-page.h
Labels: bug, enhancement

#1216 [Add] 『精神病院院長』 / the Director of Mental Hospital
  lib/edit/r_info.txt
Labels: enhancement

#1221 Merge/hengband20211012
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  src/Makefile.am
  src/birth/character-builder.cpp
  src/core/game-play.cpp
  src/info-reader/artifact-reader.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/info-reader-util.cpp
  src/info-reader/info-reader-util.h
  src/info-reader/kind-reader.cpp
  src/info-reader/race-reader.cpp
  src/io-dump/character-dump.cpp
  src/io-dump/random-art-info-dumper.cpp
  src/io/input-key-processor.cpp
  src/knowledge/knowledge-inventory.cpp
  src/knowledge/knowledge-self.cpp
  src/load/store-loader.cpp
  src/market/building-initializer.cpp
  src/mutation/mutation-processor.cpp
  src/player/process-death.cpp
  src/room/rooms-city.cpp
  src/room/rooms-vault.cpp
  src/store/black-market.cpp
  src/store/cmd-store.cpp
  src/store/home.cpp
  src/store/home.h
  src/store/museum.cpp
  src/store/pricing.cpp
  src/store/purchase-order.cpp
  src/store/say-comments.cpp
  src/store/sell-order.cpp
  src/store/service-checker.cpp
  src/store/store-key-processor.cpp
  src/store/store-util.cpp
  src/store/store-util.h
  src/store/store.cpp
  src/store/store.h
  src/util/enum-range.h
  src/view/display-store.cpp
  src/world/world-turn-processor.cpp
Labels: enhancement

#1223 [Add] ドラゴン・ビキニ / Dragon Bikini (ただしapply_magic処理がうまく働いていない)
  lib/edit/k_info.txt
  src/floor/floor-events.cpp
  src/knowledge/knowledge-inventory.cpp
  src/object-enchant/apply-magic-armor.cpp
  src/sv-definition/sv-armor-types.h
Labels: enhancement

#1225 [Add] ケツ妹子 / Ketsu imoko
  lib/edit/r_info.txt
Labels: enhancement

#1235 [Add] 跳刃地背拳の使い手『フォックス』 / Fox, the Camouflaged Death and Jumping Attack Arts
  lib/edit/r_info.txt
Labels: enhancement

#1241 [Implement] 宿で即惰眠をむさぼり続けると50日くらいで世界こわれる程度に時空崩壊度加算。
  src/cmd-building/cmd-inn.cpp
Labels: enhancement

#1263 [add]オレンジ色の水晶像 / Orange crystal statue
  lib/edit/r_info.txt
Labels: enhancement

#1264 [Add] 算数教師『バルディ先生』 / Mr.Baldi, the Arithmetic Teacher
  lib/edit/r_info.txt
Labels: enhancement

#1268 [Add] クッキーおばあちゃん / Cookie grandma
  lib/edit/k_info.txt
  lib/edit/r_info.txt
Labels: enhancement

#1273 [Add] 『しんのゆうしゃ』 / the Truly Brave Knight
  lib/edit/r_info.txt
  src/cmd-building/cmd-inn.cpp
Labels: enhancement

#1324 Feature/add monster mur binzyou buddhism
  lib/edit/r_info.txt
Labels: enhancement

#1327 [Alliance][Implement] アライアンスに基本勢力値を実装。
  src/alliance/alliance.cpp
  src/alliance/alliance.h
  src/cmd-io/cmd-knowledge.cpp
  src/knowledge/knowledge-alliance.cpp
Labels: enhancement

#1331 Feature/refactor world collapsion
  src/cmd-building/cmd-inn.cpp
  src/load/load.cpp
  src/save/save.cpp
  src/view/display-player-middle.cpp
  src/wizard/cmd-wizard.cpp
  src/world/world-collapsion.cpp
  src/world/world-collapsion.h
  src/world/world-turn-processor.cpp
  src/world/world.cpp
  src/world/world.h
Labels: enhancement

#1332 Feature/add alliance jural
  lib/edit/r_info.txt
  src/alliance/alliance.cpp
  src/alliance/alliance.h
Labels: enhancement

#1335 [Monster][Add] 拳王親衛隊2名追加。
  lib/edit/r_info.txt
Labels: enhancement

#1336 [Feature][Add] 水田/paddy field
  lib/edit/f_info.txt
Labels: enhancement
