Repository deskull-m/bakabakaband, pull requests merged in 2025-04, with the labels that each got.

#5812 変愚「変愚「[Refactor] str_tolower()のシグネチャの変更 #4773」のマージ」のマージ
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-finder.cpp
  src/core/show-file.cpp
  src/core/show-file.h
  src/util/string-processor.cpp
  src/util/string-processor.h
  src/wizard/wizard-item-modifier.cpp
Labels: enhancement

#5816 変愚「カメレオンの変身先選択ルーチンをdo_get_mon_num_prep() から分離した #4765」のマージ
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-list.cpp
  src/monster/monster-list.h
  src/monster/monster-processor.cpp
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/system/enums/monrace/monrace-hook-types.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
Labels: enhancement

#5818 変愚「[Refactor] do_cmd_query_symbol #4776」のマージ
  src/cmd-io/cmd-lore.cpp
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
Labels: enhancement

#5820 変愚「ダンジョン突入フラグが反対になっていたのを修正した #4783」のマージ
  src/system/services/dungeon-service.cpp
Labels: enhancement

#5821 (Vault)[Add] 庭園
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5822 (Vault)[Add] 毒池
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5823 (Vault)[Add] ガラス壁
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5825 変愚「[Feature] デバッグコマンドでモンスターを選択しやすくする #4777」のマージ
  src/system/monrace/monrace-list.cpp
  src/wizard/wizard-spells.cpp
Labels: enhancement

#5827 変愚「[Fix] 闘技場の地形が正しく生成されない #4785」のマージ
  src/floor/floor-generator.cpp
Labels: enhancement

#5829 変愚「cave_has_flag_bold() をFloorType::has_terrain_characteristics() へ繰り込んだ #4766」のマージ
  src/action/run-execution.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-building/cmd-building.cpp
  src/combat/shoot.cpp
  src/dungeon/quest-completion-checker.cpp
  src/dungeon/quest.cpp
  src/effect/effect-processor.cpp
  src/floor/cave.cpp
  src/floor/cave.h
  src/grid/feature-generator.cpp
  src/grid/feature.cpp
  src/mind/mind-elementalist.cpp
  src/monster-floor/monster-lite.cpp
  src/mspell/mspell-judgement.cpp
  src/object-activation/activation-bolt-ball.cpp
  src/object-use/throw-execution.cpp
  src/player-attack/player-attack.cpp
  src/realm/realm-hissatsu.cpp
  src/room/cave-filler.cpp
  src/room/treasure-deployment.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-neighbor.cpp
  src/spell-realm/spells-chaos.cpp
  src/spell-realm/spells-crusade.cpp
  src/spell/spells-status.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/target/projection-path-calculator.cpp
Labels: enhancement

#5831 変愚「[Feature] INIからのsavefile読込を拡張する #4791」のマージ
  src/main-win.cpp
Labels: enhancement

#5833 (Vault)[Add] トラップ部屋
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5834 (Vault)[Add] 水路
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5836 変愚「特殊なモンスター生成フィルタを個別のフィルタ関数に分割した #4778」のマージ
  src/floor/cave-generator.cpp
  src/floor/floor-generator.cpp
  src/floor/wild.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-summon.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/player/eldritch-horror.cpp
Labels: enhancement

#5838 変愚「get_monster_hook() を廃止した #4793」のマージ
  src/birth/inventory-initializer.cpp
  src/core/player-processor.cpp
  src/dungeon/quest.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/object-enchant/others/apply-magic-others.cpp
  src/player/eldritch-horror.cpp
  src/room/rooms-special.cpp
  src/system/building-type-definition.cpp
  src/system/enums/monrace/monrace-hook-types.h
Labels: enhancement

#5840 変愚「function型の引数を取るget_mon_num_prep() を廃止した #4794」のマージ
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/room/pit-nest-util.h
  src/room/rooms-nest.cpp
  src/room/rooms-pit.cpp
  src/system/enums/monrace/monrace-hook-types.h
Labels: enhancement

#5841 (Vault)[Add] 庭園
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5842 (Vault)[Add] ボス部屋
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5844 変愚「 function型の引数を取るget_mon_num_prep() を廃止した #4794」のマージ
  src/effect/effect-processor.cpp
  src/mspell/mspell-judgement.cpp
  src/spell/range-calc.cpp
  src/spell/range-calc.h
Labels: enhancement

#5846 変愚「project() の中身を調整した #4798」
  src/effect/effect-processor.cpp
Labels: enhancement

#5848 変愚「FloorType::has_terrain_characteristics() を呼び出している関数を整形した その2 #4801」
  src/cmd-action/cmd-move.cpp
  src/cmd-building/cmd-building.cpp
  src/grid/feature-generator.cpp
  src/grid/feature.cpp
  src/market/building-service.cpp
  src/market/building-service.h
  src/mind/mind-elementalist.cpp
  src/room/cave-filler.cpp
  src/spell-kind/earthquake.cpp
Labels: enhancement

#5850 [Refactor] update_mon_lite() を整形した
  src/monster-floor/monster-lite-util.cpp
  src/monster-floor/monster-lite-util.h
  src/monster-floor/monster-lite.cpp
Labels: enhancement

#5851 (Vault)[Add] ボス部屋
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5855 変愚「FloorType::has_terrain_characteristics() を呼び出している関数を整形した その3 #4807」のマージ
  src/action/run-execution.cpp
  src/combat/shoot.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/melee/melee-spell-util.cpp
  src/melee/melee-spell-util.h
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-judgement.h
  src/mspell/mspell-lite.cpp
  src/player-attack/player-attack.cpp
  src/spell-realm/spells-chaos.cpp
  src/target/projection-path-calculator.cpp
  src/target/projection-path-calculator.h
Labels: enhancement

#5857 [Fix] `NEVER_BLOW` フラグ抜け修正。
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-reader.cpp
Labels: bug, enhancement

#5859 変愚「モンスター生成フィルタ用のグローバル関数解体 その1 (B案) #4808」のマージ
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  lib/edit/MonraceDefinitions.jsonc
  src/Makefile.am
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/monrace/monrace-allocation.cpp
  src/system/monrace/monrace-allocation.h
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/services/dungeon-monrace-service.cpp
  src/system/services/dungeon-monrace-service.h
Labels: enhancement

#5861 変愚「[Fix] 合体ユニークの倒した数の記録の扱いがあいまい #4806」のマージ
  src/monster/monster-damage.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/monrace/monrace-list.cpp
Labels: enhancement

#5863 変愚「ターゲッティングが正しく実行できない不具合を修正した #4810」のマージ
  src/target/projection-path-calculator.cpp
Labels: enhancement

#5864 (Vault)[Add] 船型部屋
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5866 変愚「[Refactor] 死亡済みのユニークモンスターかどうかの判定 #4812」のマージ
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest.cpp
  src/floor/object-allocator.cpp
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-monsters.cpp
  src/load/load-zangband.cpp
  src/lore/lore-util.cpp
  src/mspell/summon-checker.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/monrace/monrace-list.cpp
Labels: enhancement

#5867 (Vault)[Add] 集合住宅
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5869 変愚「FloorType::has_terrain_characteristics() を呼び出している関数を整形した その4 #4809」のマージ
  src/grid/feature-generator.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-judgement.h
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-realm/spells-crusade.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: enhancement

#5871 変愚「For descriptions, immunities and vulnerabilities override resistances #4741」のマージ
  src/perception/identification.cpp
Labels: enhancement

#5875 変愚「English: skip article in tombstone explanation when hallucinating #4814」のマージ
  src/player/player-damage.cpp
Labels: enhancement

#5877 変愚「モンスター生成フィルタ用のグローバル関数解体 その2 #4817」のマージ
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
Labels: enhancement

#5878 (Vault)[Add] 虫状部屋
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5880 変愚「[Feature] 分離先ユニークを単体で出現可能にする #4818」のマージ
  src/monster-floor/monster-remover.cpp
  src/monster/monster-list.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
Labels: enhancement

#5882 変愚「scatter() の引数と戻り値をPos2D に差し替えた #4815」のマージ
  src/alliance/alliance.cpp
  src/dungeon/quest-completion-checker.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-util.cpp
  src/floor/floor-util.h
  src/mind/mind-elementalist.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-death-util.cpp
  src/monster-floor/monster-death-util.h
  src/monster-floor/monster-generator.cpp
  src/monster-floor/special-death-switcher.cpp
  src/mspell/specified-summon.cpp
  src/object-activation/activation-bolt-ball.cpp
  src/player/player-status.cpp
  src/realm/realm-crusade.cpp
  src/room/vault-builder.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-neighbor.cpp
  src/wizard/wizard-spells.cpp
Labels: enhancement

#5884 変愚「filter_monrace_hook2() を解体した #4820」のマージ
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
Labels: enhancement

#5885 (Vault)[Add] 宝物庫
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5887 変愚「FloorType::has_terrain_characteristics() を呼び出している関数を整形した その5 #4819」のマージ
  src/object-use/throw-execution.cpp
  src/room/rooms-maze-vault.cpp
  src/room/rooms-vault.cpp
  src/room/treasure-deployment.cpp
  src/room/treasure-deployment.h
  src/util/point-2d.h
Labels: enhancement

#5889 変愚「[Refactor] Point2D型の2点間の中点を取る関数 #4824」のマージ
  src/room/treasure-deployment.cpp
  src/util/point-2d.h
Labels: enhancement

#5891 変愚「[Fix] ランダムVault生成でクラッシュ #4826」のマージ
  src/room/rooms-vault.cpp
Labels: enhancement

#5893 変愚「FloorType/Grid/TerrainType クラスの依存関係を整理した #4821」のマージ
  src/action/movement-execution.cpp
  src/action/open-close-execution.cpp
  src/action/travel-execution.cpp
  src/action/tunnel-execution.cpp
  src/cmd-action/cmd-open-close.cpp
  src/combat/shoot.cpp
  src/effect/effect-feature.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/floor/wild.cpp
  src/grid/feature-generator.cpp
  src/grid/grid.cpp
  src/grid/trap.cpp
  src/info-reader/dungeon-reader.cpp
  src/io/cursor.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-berserker.cpp
  src/monster-floor/monster-lite.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/mspell/mspell-lite.cpp
  src/object/warning.cpp
  src/pet/pet-fall-off.cpp
  src/player/player-move.cpp
  src/realm/realm-hissatsu.cpp
  src/room/rooms-special.cpp
  src/room/rooms-vault.cpp
  src/room/vault-builder.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-realm/spells-chaos.cpp
  src/store/cmd-store.cpp
  src/system/enums/terrain/terrain-characteristics.h
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/system/terrain/terrain-definition.cpp
  src/system/terrain/terrain-definition.h
  src/target/grid-selector.cpp
Labels: enhancement

#5895 変愚「自動拾い関係の引数からPlayerType を掃き出した #4829」のマージ #5894
  src/autopick/autopick-editor-command.cpp
  src/autopick/autopick-reader-writer.cpp
  src/autopick/autopick-reader-writer.h
  src/autopick/autopick-registry.cpp
  src/cmd-io/cmd-autopick.cpp
  src/core/show-file.cpp
  src/util/angband-files.cpp
  src/util/angband-files.h
Labels: enhancement

#5897 変愚「モンスター生成フィルタ用のグローバル関数解体 その3 #4822」のマージ
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
Labels: enhancement

#5899 変愚「[Refactor] fill_treasureの引数をRect2D型にする #4830」のマージ
  src/room/rooms-maze-vault.cpp
  src/room/rooms-vault.cpp
  src/room/treasure-deployment.cpp
  src/room/treasure-deployment.h
  src/util/point-2d.h
Labels: enhancement

#5901 変愚「モンスター生成フィルタ用のグローバル関数解体 その4 #4832」のマージ
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
Labels: enhancement

#5903 変愚「地形IDを動的に引く仕組みの構築 その8 #4823」のマージ
  src/effect/effect-feature.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-streams.cpp
  src/floor/object-allocator.cpp
  src/floor/wild.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/grid/grid.cpp
  src/info-reader/feature-reader.cpp
  src/monster/monster-processor.cpp
  src/room/cave-filler.cpp
  src/room/rooms-special.cpp
  src/room/rooms-vault.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
Labels: enhancement

#5905 変愚「地形IDを動的に引く仕組みの構築 その9 #4835」のマージ
  src/floor/object-allocator.cpp
  src/floor/wild.cpp
  src/grid/door.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-reader.cpp
  src/room/rooms-vault.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
Labels: enhancement

#5907 変愚「モンスター生成フィルタ用のグローバル関数解体 その5 #4833」のマージ
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
Labels: enhancement

#5909 変愚「[Feature] 自動拾いエディタでのhome/endキーの挙動を一般的なものにする #4838」のマージ
  src/cmd-io/cmd-autopick.cpp
  src/cmd-visual/cmd-draw.cpp
  src/core/asking-player.cpp
  src/core/show-file.cpp
  src/io/input-key-acceptor.cpp
  src/io/input-key-acceptor.h
Labels: enhancement

#5911 変愚「モンスター生成フィルタ用のグローバル関数解体 その6 #4839」のマージ
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
Labels: enhancement

#5912 変愚「モンスター生成フィルタ用のグローバル関数解体 その6 #4839」のマージ その２
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-item/cmd-eat.cpp
  src/player-info/race-info.h
  src/system/item-entity.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
Labels: enhancement

#5914 変愚「地形IDを動的に引く仕組みの構築 その10 #4840」のマージ
  src/effect/effect-feature.cpp
  src/floor/floor-streams.cpp
  src/floor/wild.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-reader.cpp
  src/room/cave-filler.cpp
  src/room/rooms-vault.cpp
Labels: enhancement

#5916 変愚「日付変更時に日替わり賞金首が確定できない不具合を修正した #4844」のマージ
  src/monster/monster-util.cpp
Labels: enhancement

#5918 変愚「川生成ルーチン周りをTerrainTag を使って改善した #4841」のマージ
  src/floor/floor-streams.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
Labels: enhancement

#5919 (Vault)[Add] 宝物庫
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5920 (Vault)[Add] ボス部屋
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5922 変愚「モンスター生成フィルタ用のグローバル関数解体 その7 #4843」のマージ
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/room/pit-nest-util.h
  src/room/rooms-nest.cpp
  src/room/rooms-pit.cpp
  src/system/enums/monrace/monrace-hook-types.h
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
Labels: enhancement

#5923 (Vault)[Add] 水路
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5924 (Vault)[Add] 水路
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5926 変愚「地形IDを動的に引く仕組みの構築 その12 #4848」のマージ
  src/effect/effect-feature.cpp
  src/floor/floor-streams.cpp
  src/floor/wild.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-info-tokens-table.cpp
  src/info-reader/feature-reader.cpp
  src/load/floor-loader.cpp
  src/room/cave-filler.cpp
  src/system/enums/terrain/terrain-tag.h
Labels: enhancement

#5928 変愚「[Refactor] distance() #4849」のマージ
  src/core/object-compressor.cpp
  src/dungeon/quest-monster-placer.cpp
  src/effect/effect-processor.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/floor/geometry.cpp
  src/floor/geometry.h
  src/floor/tunnel-generator.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-mirror-master.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-lite.cpp
  src/mspell/mspell-selector.cpp
  src/object/warning.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-hissatsu.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-vault.cpp
  src/room/treasure-deployment.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-launcher.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-realm/spells-crusade.cpp
  src/spell/range-calc.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/target/target-setter.cpp
Labels: enhancement

#5930 変愚「[Refactor] target_set_prepare()のシグネチャ変更 #4851」のマージ
  src/target/target-preparation.cpp
  src/target/target-preparation.h
  src/target/target-setter.cpp
Labels: enhancement

#5932 変愚「地形IDを動的に引く仕組みの構築 その13 #4853」のマージ
  src/action/movement-execution.cpp
  src/action/open-close-execution.cpp
  src/action/travel-execution.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/combat/shoot.cpp
  src/core/game-play.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-object.cpp
  src/floor/floor-util.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/grid/grid.cpp
  src/grid/grid.h
  src/grid/trap.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/feature-reader.cpp
  src/io/cursor.cpp
  src/io/interpret-pref-file.cpp
  src/io/screen-util.cpp
  src/knowledge/knowledge-features.cpp
  src/mind/mind-berserker.cpp
  src/mind/mind-mirror-master.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/object/warning.cpp
  src/player-status/player-speed.cpp
  src/player/player-move.cpp
  src/realm/realm-hissatsu.cpp
  src/room/rooms-builder.cpp
  src/spell/range-calc.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/view/display-map.cpp
  src/window/main-window-util.cpp
  src/window/main-window-util.h
Labels: enhancement

#5934 変愚「[Refactor] プレイ時間をElapsedTimeクラスで管理する #4861」のマージ
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  src/Makefile.am
  src/birth/character-builder.cpp
  src/cmd-io/cmd-autopick.cpp
  src/cmd-visual/cmd-draw.cpp
  src/core/game-closer.cpp
  src/core/game-play.cpp
  src/dungeon/quest.cpp
  src/knowledge/knowledge-self.cpp
  src/load/extra-loader.cpp
  src/load/load.cpp
  src/monster-floor/monster-death.cpp
  src/save/player-writer.cpp
  src/save/save.cpp
  src/util/elapsed-time.cpp
  src/util/elapsed-time.h
  src/window/display-sub-windows.cpp
  src/world/world-movement-processor.cpp
  src/world/world.cpp
  src/world/world.h
Labels: enhancement

#5936 変愚「Nest 関係のモンスター生成フィルタをMonraceDefinition のオブジェクトメソッドに繰り込んだ #4857」のマージ
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
Labels: enhancement

#5938 変愚「地形IDを動的に引く仕組みの構築 その14 #4863」のマージ
  src/floor/floor-leaver.cpp
  src/floor/pattern-walk.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/grid/grid.cpp
  src/grid/grid.h
  src/grid/trap.cpp
  src/grid/trap.h
  src/info-reader/feature-reader.cpp
  src/load/old/load-v1-5-0.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/player/player-status.cpp
  src/room/rooms-pit.cpp
  src/room/rooms-trap.cpp
  src/room/rooms-vault.cpp
  src/spell-kind/spells-grid.cpp
  src/system/enums/terrain/terrain-tag.h
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/system/terrain/terrain-list.cpp
  src/system/terrain/terrain-list.h
Labels: enhancement

#5940 変愚「[Refactor] ty_type を TargetSetter クラスにする #4859」のマージ
  src/target/target-setter.cpp
Labels: enhancement

#5942 変愚「feat_door に関するタグ文字列をTerrainTag に変換した #4866」のマージ
  src/effect/effect-feature.cpp
  src/grid/door.cpp
  src/grid/door.h
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-info-tokens-table.cpp
  src/info-reader/feature-reader.cpp
  src/room/door-definition.cpp
  src/room/door-definition.h
  src/room/rooms-builder.cpp
  src/room/rooms-nest.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-pit.cpp
  src/room/rooms-special.cpp
  src/room/rooms-vault.cpp
  src/system/grid-type-definition.cpp
Labels: enhancement

#5944 変愚「[Refactor] los()のシグネチャを変更 #4867」のマージ
  src/effect/effect-monster-psi.cpp
  src/effect/effect-processor.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-util.cpp
  src/floor/line-of-sight.cpp
  src/floor/line-of-sight.h
  src/melee/melee-spell-flags-checker.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/quantum-effect.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-lite.cpp
  src/player/player-view.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell/range-calc.cpp
  src/spell/range-calc.h
  src/spell/spells-summon.cpp
  src/target/target-setter.cpp
Labels: enhancement

#5946 変愚「[Refactor] in_disintegration_range()のシグネチャを変更 #4869」のマージ
  src/effect/effect-processor.cpp
  src/monster-floor/monster-direction.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-lite.cpp
  src/spell-realm/spells-crusade.cpp
  src/spell/range-calc.cpp
  src/spell/range-calc.h
Labels: enhancement

#5947 (Vault)[Add] 対称部屋
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5949 変愚「DoorKind 周りのラップアップ #4870」のマージ
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  src/Makefile.am
  src/effect/effect-feature.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-generator.cpp
  src/grid/door.cpp
  src/grid/door.h
  src/grid/feature-generator.cpp
  src/grid/feature.h
  src/info-reader/dungeon-reader.cpp
  src/info-reader/feature-reader.cpp
  src/info-reader/general-parser.cpp
  src/room/door-definition.h
  src/room/rooms-builder.cpp
  src/room/rooms-nest.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-pit.cpp
  src/room/rooms-special.cpp
  src/room/rooms-vault.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-grid.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/enums/terrain/terrain-kind.h
  src/system/enums/terrain/terrain-tag.h
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/system/terrain/terrain-list.cpp
  src/system/terrain/terrain-list.h
Labels: enhancement

#5951 変愚「project()内での軌道保持方法のリファクタリング #4873」のマージ
  src/effect/effect-processor.cpp
  src/mspell/mspell-judgement.cpp
  src/spell/range-calc.cpp
  src/spell/range-calc.h
Labels: enhancement

#5954 (Vault)[Add] 対称部屋
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5955 (Vault)[Add] 水路
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5953 変愚「自動拾い関係のconcptr をstring に変えた #4831」のマージ
  src/autopick/autopick-drawer.cpp
  src/autopick/autopick-editor-command.cpp
  src/autopick/autopick-editor-util.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-entry.h
  src/autopick/autopick-finder.cpp
  src/autopick/autopick-finder.h
  src/autopick/autopick-inserter-killer.cpp
  src/autopick/autopick-reader-writer.cpp
  src/autopick/autopick-reader-writer.h
  src/autopick/autopick-registry.cpp
  src/autopick/autopick-util.cpp
  src/autopick/autopick-util.h
  src/cmd-io/cmd-autopick.cpp
  src/knowledge/knowledge-autopick.cpp
Labels: enhancement

#5957 変愚「monraces_info を絶滅させた #4872」のマージ
  src/alliance/alliance-jural.cpp
  src/alliance/alliance.cpp
  src/cmd-item/cmd-eat.cpp
  src/io/files-util.cpp
  src/knowledge/knowledge-alliance.cpp
  src/load/old/monster-loader-savefile50.cpp
  src/lore/lore-store.cpp
  src/main/info-initializer.cpp
  src/market/building-quest.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-summon.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-processor.cpp
  src/mspell/assign-monster-spell.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/mspell/mspell-summon.cpp
  src/mspell/specified-summon.cpp
  src/mspell/summon-checker.cpp
  src/room/pit-nest-util.cpp
  src/room/pit-nest-util.h
  src/room/rooms-nest.cpp
  src/room/rooms-pit.cpp
  src/save/save.cpp
  src/spell-kind/spells-polymorph.cpp
  src/store/rumor.cpp
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
  src/system/monster-entity.cpp
  src/window/main-window-util.cpp
  src/wizard/wizard-game-modifier.cpp
Labels: enhancement

#5959 変愚「[Fix] 自動拾いエディタの横スクロールの挙動がおかしい #4878」のマージ
  src/autopick/autopick-drawer.cpp
Labels: enhancement

#5961 変愚「モンスター生成フィルタを全てMonraceDefinition に繰り込み、monster-race-hook.cpp/h を廃止した #4889」のマージ
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/room/pit-nest-util.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/util/string-processor.cpp
  src/util/string-processor.h
  src/view/display-symbol.h
Labels: enhancement

#5962 (Vault)[Add] 部屋群
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5964 変愚「[Refactor/Fix] 文字入力処理 #4879」のマージ
  src/autopick/autopick-editor-command.cpp
  src/autopick/autopick-finder.cpp
  src/core/asking-player.cpp
Labels: enhancement

#5966 変愚「Doors クラスを作ってシングルトン化した #4876」のマージ
  src/effect/effect-feature.cpp
  src/grid/door.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-reader.cpp
  src/room/door-definition.cpp
  src/room/door-definition.h
  src/room/rooms-normal.cpp
  src/system/grid-type-definition.cpp
Labels: enhancement

#5967 (Vault)[Add] 水路
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5969 変愚「[Refactor] コピーされるべきでないクラスのコピーコンストラクタ/コピー代入演算子の削除 #4881」のマージ
  src/info-reader/artifact-reader.cpp
  src/monster/monster-processor.cpp
  src/monster/monster-util.cpp
  src/object-enchant/object-ego.h
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/system/baseitem/baseitem-definition.h
  src/system/monrace/monrace-definition.h
Labels: enhancement

#5970 (Vault)[Add] 庭園
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#5972 変愚「[Feature] 自動拾いエディタのカーソル上下の挙動を自然にする #4880」のマージ
  src/autopick/autopick-util.h
  src/cmd-io/cmd-autopick.cpp
Labels: enhancement

#5974 変愚「[Refactor] dist_to_line()のシグネチャ #4883」のマージ
  src/effect/effect-processor.cpp
  src/spell/range-calc.cpp
  src/spell/range-calc.h
Labels: enhancement

#5976 変愚「ダンジョンごとに地形IDを差し替えていたグローバル変数をDungeonDefinition へ繰り込み、feature.cpp/h ファイルを廃止した #4877」のマージ
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  src/Makefile.am
  src/core/game-play.cpp
  src/dungeon/quest-completion-checker.cpp
  src/effect/effect-feature.cpp
  src/flavor/tval-description-switcher.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-generator.cpp
  src/floor/pattern-walk.cpp
  src/floor/wild.cpp
  src/floor/wild.h
  src/grid/door.cpp
  src/grid/feature-generator.cpp
  src/grid/feature-generator.h
  src/grid/feature.cpp
  src/grid/feature.h
  src/grid/grid.cpp
  src/grid/grid.h
  src/info-reader/dungeon-reader.cpp
  src/monster/monster-processor.cpp
  src/player/player-status.cpp
  src/room/cave-filler.cpp
  src/room/rooms-city.cpp
  src/room/rooms-city.h
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-grid.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/dungeon/dungeon-list.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/wizard/wizard-special-process.cpp
Labels: enhancement

#5978 変愚「[Refactor] 床と壁の確率による選択 #4885」のマージ
  src/info-reader/dungeon-reader.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/dungeon/dungeon-list.cpp
Labels: enhancement

#5980 変愚「Grid::get_feat_mimic() をget_terrain_id() に吸収合併した #4888」のマージ
  src/action/run-execution.cpp
  src/spell-kind/spells-floor.cpp
  src/system/floor/floor-info.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/target/target-describer.cpp
Labels: enhancement

#5982 変愚「[Fix] add_door呼び出しでクラッシュ #4891」のマージ
  src/room/rooms-vault.cpp
Labels: enhancement

#5984 変愚「[Feature] 分解のブレス/ボールの軌道の表示を自然にする #4886」のマージ
  src/effect/effect-processor.cpp
Labels: enhancement

#5986 変愚「in_bounds() の周辺コードを整備した その1 #4890」のマージ
  src/core/player-processor.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/floor/floor-util.h
  src/mind/mind-elementalist.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-grid.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/target/grid-selector.cpp
Labels: enhancement

#5988 変愚「drop_near() の引数をPos2D に変え、chance の引数をoptional に変えた #4887」のマージ
  src/action/open-close-execution.cpp
  src/artifact/fixed-art-generator.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-item/cmd-eat.cpp
  src/combat/shoot.cpp
  src/dungeon/quest-completion-checker.cpp
  src/effect/effect-monster.cpp
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/floor/geometry.cpp
  src/floor/geometry.h
  src/inventory/inventory-object.cpp
  src/inventory/pack-overflow.cpp
  src/mind/mind-chaos-warrior.cpp
  src/mind/mind-hobbit.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-object.cpp
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-safety-hiding.h
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
  src/monster-floor/special-death-switcher.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-processor.cpp
  src/object-use/throw-execution.cpp
  src/player/player-damage.cpp
  src/realm/realm-nature.cpp
  src/specific-object/chest.cpp
  src/spell/spells-object.cpp
  src/spell/spells-status.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/util/point-2d.h
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: enhancement

#5990 変愚「sweep_ranged_attack_grid() の引数をPos2D に変え、戻り値をoptional<Pos2D> に変えた #4893」のマージ
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
Labels: enhancement

#5992 変愚「マルチバイト文字の入出力をchar\* からstring_view に変えた #4892」のマージ
  src/main-win.cpp
  src/main-win/graphics-win.cpp
  src/main-win/graphics-win.h
  src/main-win/main-win-bg.cpp
  src/main-win/main-win-exception.cpp
  src/main-win/main-win-music.cpp
  src/main-win/main-win-utils.h
  src/util/angband-files.cpp
Labels: enhancement

#5994 変愚「[Refactor] 距離nの座標のオフセット配列 #4895」のマージ
  src/monster-floor/monster-dist-offsets.cpp
  src/monster-floor/monster-dist-offsets.h
  src/monster-floor/monster-safety-hiding.cpp
Labels: enhancement

#5996 変愚「[Fix] build_bubble_value() でクラッシュ #4898」のマージ
  src/room/rooms-vault.cpp
Labels: enhancement

#5998 変愚「MonsterSweepGrid のメソッドからポインタ引数を掃き出した #4900」のマージ
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
Labels: enhancement

#6000 変愚「表示が崩れる不具合の修正 #4903」のマージ
  src/main-win.cpp
Labels: enhancement

#6002 変愚「in_bounds() の周辺コードを整備した その2 #4902」のマージ
  src/effect/effect-feature.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-changer.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/mind/mind-elementalist.cpp
  src/mind/mind-ninja.cpp
  src/monster/monster-list.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-lite.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
Labels: enhancement

#6003 (Vault)[Add] 庭園
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#6005 変愚「[Fix] 影移動の魔法が特定の位置関係で失敗する #4907」のマージ
  src/realm/realm-hex.cpp
Labels: enhancement

#6007 変愚「[Refactor] モンスターの移動先決定処理 #4904」のマージ
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-safety-hiding.h
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
Labels: enhancement

#6009 変愚「[Fix] ターゲット選択時の挙動がおかしい #4913」のマージ
  src/target/target-setter.cpp
Labels: enhancement

#6011 変愚「wt_type をenum class に変えた #4909」のマージ
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  src/Makefile.am
  src/floor/wild.cpp
  src/floor/wild.h
  src/monster/monster-util.cpp
  src/system/enums/terrain/wilderness-terrain.h
Labels: enhancement

#6013 変愚「in_bounds() の周辺コードを整備した その3 #4916」のマージ
  src/floor/fixed-map-generator.cpp
  src/floor/floor-streams.cpp
  src/floor/object-scanner.cpp
  src/floor/object-scanner.h
  src/grid/door.cpp
  src/grid/grid.h
  src/monster-floor/monster-remover.cpp
  src/monster-floor/monster-remover.h
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-teleport.cpp
Labels: enhancement

#6015 変愚「AngbandSystem/FloorType へPlayerType に属していたフィールド変数を移した #4910」のマージ
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-move.cpp
  src/core/game-closer.cpp
  src/core/game-play.cpp
  src/dungeon/dungeon-processor.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/wild.cpp
  src/io/exit-panic.cpp
  src/io/signal-handlers.cpp
  src/load/load.cpp
  src/load/world-loader.cpp
  src/main-win.cpp
  src/save/player-writer.cpp
  src/save/save.cpp
  src/system/angband-system.cpp
  src/system/angband-system.h
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/player-type-definition.h
  src/world/world-movement-processor.cpp
Labels: enhancement

#6017 変愚「display-monster-status.cpp/h を廃止した #4917」のマージ
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  src/Makefile.am
  src/knowledge/knowledge-monsters.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/target/target-describer.cpp
  src/view/display-monster-status.cpp
  src/view/display-monster-status.h
Labels: enhancement

#6019 変愚「wild.cpp/h の構造体と関数の整理 #4915」のマージ
  src/floor/fixed-map-generator.cpp
  src/floor/wild.cpp
  src/floor/wild.h
  src/main/info-initializer.cpp
Labels: enhancement

#6021 変愚「polymorph_of_chameleon() の引数で出ていた警告を除去した #4919」のマージ
  src/monster/monster-list.cpp
Labels: enhancement

#6024 Vault/20250425
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#6023 変愚「std::span のコンストラクタ呼び出しに関する調整 #4912」のマージ
  .github/workflows/build-with-autotools.yml
  .github/workflows/create-cache-for-ccache.yml
  .github/workflows/pull-request-status-check.yml
  src/info-reader/dungeon-reader.cpp
  src/mind/mind-chaos-warrior.cpp
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster/monster-processor.cpp
  src/player-base/player-class.cpp
  src/spell-kind/spells-polymorph.cpp
  src/system/baseitem/baseitem-list.cpp
  src/system/baseitem/baseitem-list.h
  src/term/gameterm.cpp
  src/term/z-form.cpp
  src/util/abstract-map-wrapper.h
  src/util/abstract-vector-wrapper.h
  src/util/sha256.cpp
  src/view/display-map.cpp
Labels: enhancement

#6025 (Vault)[Add] 水路
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#6027 変愚「[Fix] 十字型の部屋の内部の小部屋の下側の壁がない #4921」のマージ
  src/room/rooms-normal.cpp
Labels: enhancement

#6028 (Vault)[Fix] Vaultの番号振りミスを修正
  lib/edit/VaultDefinitions.txt
Labels: bug

#6030 変愚「in_bounds() が呼ばれている箇所の周辺コードを整備した その4 #4918」のマージ
  src/floor/tunnel-generator.cpp
  src/floor/tunnel-generator.h
  src/grid/trap.cpp
  src/room/vault-builder.cpp
Labels: enhancement

#6032 変愚「[Refactor] 方向ベクトルとそれを使用する処理 #4923」のマージ
  src/action/open-util.cpp
  src/action/travel-execution.cpp
  src/cmd-action/cmd-travel.cpp
  src/effect/effect-feature.cpp
  src/floor/floor-events.cpp
  src/floor/geometry.h
  src/floor/tunnel-generator.cpp
  src/grid/feature-generator.cpp
  src/grid/grid.cpp
  src/mind/mind-warrior.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster/monster-list.cpp
  src/mutation/mutation-processor.cpp
  src/pet/pet-fall-off.cpp
  src/player-attack/player-attack.cpp
  src/player/player-move.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-hissatsu.cpp
  src/room/cave-filler.cpp
  src/room/rooms-builder.cpp
  src/room/rooms-special.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-realm/spells-chaos.cpp
  src/system/floor/floor-info.cpp
  src/target/target-getter.cpp
Labels: enhancement

#6038 変愚「[Refactor] Grid *g_ptr を Grid &grid にする #4932」のマージ
  src/action/open-util.cpp
  src/autopick/autopick.cpp
  src/autopick/autopick.h
  src/cmd-action/cmd-pet.cpp
  src/dungeon/quest-completion-checker.cpp
  src/floor/cave-generator.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-events.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-util.cpp
  src/floor/object-allocator.cpp
  src/floor/tunnel-generator.cpp
  src/grid/feature-generator.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/grid/trap.cpp
  src/inventory/floor-item-getter.cpp
  src/inventory/player-inventory.cpp
  src/io/cursor.cpp
  src/load/floor-loader.cpp
  src/mind/mind-mirror-master.cpp
  src/mind/monk-attack.cpp
  src/monster-attack/monster-attack-processor.cpp
  src/monster-attack/monster-attack-processor.h
  src/monster-floor/monster-lite.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-object.cpp
  src/monster/monster-update.cpp
  src/object/warning.cpp
  src/pet/pet-fall-off.cpp
  src/pet/pet-util.cpp
  src/pet/pet-util.h
  src/player/player-status.cpp
  src/player/player-view.cpp
  src/room/cave-filler.cpp
  src/room/rooms-builder.cpp
  src/room/rooms-city.cpp
  src/room/rooms-maze-vault.cpp
  src/room/rooms-nest.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-pit.cpp
  src/room/rooms-special.cpp
  src/room/rooms-trap.cpp
  src/room/rooms-vault.cpp
  src/room/vault-builder.cpp
  src/specific-object/torch.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/blood-curse.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-polymorph.cpp
  src/target/grid-selector.cpp
  src/window/display-sub-windows.cpp
Labels: enhancement

#6040 変愚「[Fix] RF5_HOLDがモンスターを麻痺ではなく朦朧とさせる #4933」のマージ
  src/mspell/mspell-status.cpp
Labels: enhancement

#6042 変愚「[Feature] モンスターが朦朧とする処理の修正 #4936」のマージ
  src/effect/effect-monster-resist-hurt.cpp
  src/effect/effect-monster.cpp
Labels: enhancement

#6044 変愚「[Feature] カオス耐性による混乱防御の仕様変更 #4935」のマージ
  src/effect/effect-monster.cpp
  src/effect/effect-player-resist-hurt.cpp
Labels: enhancement

#6046 変愚「[Refactor] ddx / ddy / CCW_DD を廃止し、Directionクラスで置き換える #4937」のマージ
  src/action/movement-execution.cpp
  src/action/run-execution.cpp
  src/cmd-action/cmd-travel.cpp
  src/cmd-io/cmd-floor.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/combat/shoot.cpp
  src/floor/floor-streams.cpp
  src/floor/geometry.h
  src/grid/grid.cpp
  src/io-dump/dump-util.cpp
  src/mind/mind-berserker.cpp
  src/mind/mind-force-trainer.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-move.cpp
  src/object-use/throw-execution.cpp
  src/realm/realm-hissatsu.cpp
  src/specific-object/death-crimson.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-launcher.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-realm/spells-crusade.cpp
  src/system/player-type-definition.cpp
  src/target/grid-selector.cpp
  src/target/target-getter.cpp
  src/target/target-setter.cpp
  src/view/display-map.cpp
  src/window/main-window-util.cpp
Labels: enhancement

#6052 変愚「[Feature] Rectangle2Dにイテレータを実装 #4947」のマージ
  src/room/rooms-city.cpp
  src/room/rooms-nest.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-vault.cpp
  src/room/treasure-deployment.cpp
  src/util/point-2d.h
Labels: enhancement

#6053 (Vault)[Add] ボス部屋
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#6054 (Vault)[Add] 庭園
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#6057 (Vault)[Add] ガラスの砦
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#6061 変愚「[Fix] デバッグコマンドのモンスター生成で^Iが効かないことがある #4946」のマージ
  src/wizard/wizard-spells.cpp
Labels: enhancement

#6063 変愚「[Chore] json.hppの調整 #4930」のマージ
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  THIRD-PARTY-NOTICES.txt
  src/Makefile.am
  src/external-lib/include-json.h
  src/external-lib/include/json.hpp
Labels: enhancement

#6065 変愚「{fmt} の導入 #4934」のマージ
  .github/scripts/check-format.sh
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  THIRD-PARTY-NOTICES.txt
  src/Makefile.am
  src/external-lib/fmt/format.cc
  src/external-lib/include/fmt/args.h
  src/external-lib/include/fmt/base.h
  src/external-lib/include/fmt/chrono.h
  src/external-lib/include/fmt/color.h
  src/external-lib/include/fmt/compile.h
  src/external-lib/include/fmt/core.h
  src/external-lib/include/fmt/format-inl.h
  src/external-lib/include/fmt/format.h
  src/external-lib/include/fmt/os.h
  src/external-lib/include/fmt/ostream.h
  src/external-lib/include/fmt/printf.h
  src/external-lib/include/fmt/ranges.h
  src/external-lib/include/fmt/std.h
  src/external-lib/include/fmt/xchar.h
  src/locale/localized-string.h
  src/view/display-messages.h
Labels: enhancement

#6067 変愚「WildernessGrid/Grids クラスを作っていくつかの処理を繰り込んだ #4939」
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  src/Makefile.am
  src/action/movement-execution.cpp
  src/birth/character-builder.cpp
  src/cmd-action/cmd-move.cpp
  src/core/game-play.cpp
  src/core/player-processor.cpp
  src/floor/cave-generator.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/wild.cpp
  src/floor/wild.h
  src/knowledge/knowledge-self.cpp
  src/load/world-loader.cpp
  src/main/info-initializer.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-summon.cpp
  src/monster/monster-list.cpp
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/save/save.cpp
  src/spell-kind/spells-world.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/floor/wilderness-grid.cpp
  src/system/floor/wilderness-grid.h
  src/system/player-type-definition.h
  src/wizard/wizard-special-process.cpp
  src/world/world-movement-processor.cpp
  src/world/world.h
Labels: enhancement

#6071 変愚「WildernessGrids::bottom_right/positions を廃止してRect2D に差し替えた #4950」のマージ
  src/core/game-play.cpp
  src/external-lib/include/fmt/format.h
  src/floor/wild.cpp
  src/knowledge/knowledge-self.cpp
  src/load/world-loader.cpp
  src/save/save.cpp
  src/spell-kind/spells-world.cpp
  src/system/floor/wilderness-grid.cpp
  src/system/floor/wilderness-grid.h
Labels: enhancement

#6073 変愚「MonsterEntity *m_ptr を MonsterEntity &monster にする準備 #4954」のマージ
  src/avatar/avatar-changer.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-building/cmd-inn.cpp
  src/cmd-item/cmd-eat.cpp
  src/combat/shoot.cpp
  src/core/object-compressor.cpp
  src/core/player-processor.cpp
  src/effect/effect-player-oldies.cpp
  src/floor/floor-changer.cpp
  src/grid/trap.cpp
  src/knowledge/knowledge-monsters.cpp
  src/load/old/monster-loader-savefile50.cpp
  src/load/old/monster-loader-savefile50.h
  src/melee/melee-postprocess.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-info.cpp
  src/monster/monster-info.h
  src/monster/monster-processor.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-special.cpp
  src/mutation/mutation-processor.cpp
  src/object-use/quaff/quaff-effects.cpp
  src/object-use/throw-execution.cpp
  src/player-status/player-speed.cpp
  src/player/eldritch-horror.cpp
  src/player/eldritch-horror.h
  src/player/player-move.cpp
  src/room/pit-nest-util.cpp
  src/window/display-sub-windows.cpp
  src/world/world-turn-processor.cpp
Labels: enhancement

#6075 変愚「DungeonFeeling クラスを作ってPlayerType の雰囲気関連フィールド変数を移した #4952」のマージ
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj
  Bakabakaband/Bakabakaband/Bakabakaband.vcxproj.filters
  src/Makefile.am
  src/cmd-io/cmd-dump.cpp
  src/cmd-io/feeling-table.h
  src/core/turn-compensator.cpp
  src/floor/dungeon-feeling.cpp
  src/floor/dungeon-feeling.h
  src/floor/floor-changer.cpp
  src/floor/floor-events.cpp
  src/load/floor-loader.cpp
  src/load/load-zangband.cpp
  src/load/world-loader.cpp
  src/main/scene-table-floor.cpp
  src/save/floor-writer.cpp
  src/save/player-writer.cpp
  src/system/player-type-definition.h
  src/window/main-window-left-frame.cpp
Labels: enhancement

#6077 変愚「[Feature] 例外メッセージにアイテムの詳細情報付与 #4955」のマージ
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: enhancement

#6078 (Vault)[Add] 酸の泉
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#6082 変愚「[Chore] プリコンパイルヘッダの調整 #4958」のマージ
  src/Makefile.am
  src/autopick/autopick-entry.h
  src/main-win/main-win-cfg-reader.h
  src/stdafx.h
  src/wizard/monster-info-spoiler.cpp
Labels: enhancement

#6084 変愚「Remember wilderness starting position; use it in initialize_position() #4960」のマージ
  src/birth/game-play-initializer.cpp
  src/floor/wild.cpp
  src/system/floor/wilderness-grid.cpp
  src/system/floor/wilderness-grid.h
  src/wizard/wizard-special-process.cpp
Labels: enhancement

#6086 変愚「Directionクラスの機能追加とリファクタリング #4963」のマージ
  src/action/run-execution.cpp
  src/action/run-execution.h
  src/cmd-action/cmd-move.cpp
  src/core/player-processor.cpp
  src/floor/floor-streams.cpp
  src/floor/geometry.h
  src/realm/realm-hissatsu.cpp
  src/target/target-getter.cpp
  src/target/target-getter.h
Labels: enhancement

#6087 (Vault)[Add] ドア部屋
  lib/edit/VaultDefinitions.txt
Labels: enhancement

#6092 変愚「[Refactor] 青魔法の処理をまとめる #4967」のマージ
  src/blue-magic/blue-magic-ball-bolt.cpp
  src/blue-magic/blue-magic-ball-bolt.h
  src/blue-magic/blue-magic-breath.cpp
  src/blue-magic/blue-magic-breath.h
  src/blue-magic/blue-magic-caster.cpp
  src/blue-magic/blue-magic-spirit-curse.cpp
  src/blue-magic/blue-magic-spirit-curse.h
  src/blue-magic/blue-magic-status.cpp
  src/blue-magic/blue-magic-util.cpp
  src/blue-magic/blue-magic-util.h
Labels: enhancement

#6094 変愚「[Refactor] Directionクラスの無効値の扱い #4965」のマージ
  src/action/run-execution.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/core/player-processor.cpp
  src/floor/geometry.h
Labels: enhancement
